/** Parity gate: the TS pipeline must reproduce the Python pipeline's output
 * on the sample PDFs. Fixtures are generated by web/scripts/dump.py.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";
import * as mupdf from "mupdf";

import { extractPage } from "../src/extract";
import { detect } from "../src/heuristics";
import { assignNames } from "../src/fields";
import type { Candidate, PageData } from "../src/types";

const ROOT = path.resolve(import.meta.dirname, "../..");
const EXPECTED_DIR = path.join(import.meta.dirname, "expected");
const TOL = 1.0; // geometry tolerance in points

interface Fixture {
  file: string;
  pages: any[];
}

function findPdf(stem: string): string | null {
  for (const ext of [".pdf", ".PDF"]) {
    const p = path.join(ROOT, stem + ext);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

function near(a: number, b: number, tol = TOL): boolean {
  return Math.abs(a - b) <= tol;
}

function rectNear(r: { x0: number; y0: number; x1: number; y1: number }, t: number[], tol = TOL): boolean {
  return near(r.x0, t[0], tol) && near(r.y0, t[1], tol) && near(r.x1, t[2], tol) && near(r.y1, t[3], tol);
}

function fmtRect(r: { x0: number; y0: number; x1: number; y1: number }): string {
  return `[${r.x0.toFixed(1)} ${r.y0.toFixed(1)} ${r.x1.toFixed(1)} ${r.y1.toFixed(1)}]`;
}

function diffPage(data: PageData, exp: any, errors: string[]): void {
  const p = `p${data.number + 1}`;
  if (!near(data.width, exp.width) || !near(data.height, exp.height)) {
    errors.push(`${p}: page size ${data.width}x${data.height} != ${exp.width}x${exp.height}`);
  }

  // --- text lines & spans
  if (data.lines.length !== exp.lines.length) {
    errors.push(`${p}: ${data.lines.length} lines != ${exp.lines.length} expected`);
  }
  const nLines = Math.min(data.lines.length, exp.lines.length);
  for (let i = 0; i < nLines; i++) {
    const got = data.lines[i];
    const want = exp.lines[i];
    if (!rectNear(got.bbox, want.bbox)) {
      errors.push(`${p} line ${i}: bbox ${fmtRect(got.bbox)} != [${want.bbox.map((v: number) => v.toFixed(1)).join(" ")}] (text: ${JSON.stringify(got.spans.map((s) => s.text).join(" ").slice(0, 40))})`);
    }
    if (got.spans.length !== want.spans.length) {
      errors.push(`${p} line ${i}: ${got.spans.length} spans != ${want.spans.length} `
        + `got=${JSON.stringify(got.spans.map((s) => s.text))} want=${JSON.stringify(want.spans.map((s: any) => s.text))}`);
      continue;
    }
    for (let j = 0; j < got.spans.length; j++) {
      const gs = got.spans[j];
      const ws = want.spans[j];
      if (gs.text !== ws.text) errors.push(`${p} line ${i} span ${j}: text ${JSON.stringify(gs.text)} != ${JSON.stringify(ws.text)}`);
      if (!rectNear(gs.bbox, ws.bbox)) errors.push(`${p} line ${i} span ${j} (${JSON.stringify(gs.text.slice(0, 20))}): bbox ${fmtRect(gs.bbox)} != [${ws.bbox.map((v: number) => v.toFixed(1)).join(" ")}]`);
      if (gs.bold !== ws.bold) errors.push(`${p} line ${i} span ${j} (${JSON.stringify(gs.text.slice(0, 20))}): bold ${gs.bold} != ${ws.bold}`);
    }
  }

  // --- segments
  if (data.hsegs.length !== exp.hsegs.length) {
    errors.push(`${p}: ${data.hsegs.length} hsegs != ${exp.hsegs.length} expected`);
  } else {
    for (let i = 0; i < data.hsegs.length; i++) {
      const g = data.hsegs[i];
      const w = exp.hsegs[i];
      if (!near(g.y, w.y) || !near(g.x0, w.x0) || !near(g.x1, w.x1) || g.fromText !== w.from_text) {
        errors.push(`${p} hseg ${i}: y=${g.y.toFixed(1)} x=${g.x0.toFixed(1)}..${g.x1.toFixed(1)} ft=${g.fromText} != y=${w.y.toFixed(1)} x=${w.x0.toFixed(1)}..${w.x1.toFixed(1)} ft=${w.from_text}`);
      }
    }
  }
  if (data.vsegs.length !== exp.vsegs.length) {
    errors.push(`${p}: ${data.vsegs.length} vsegs != ${exp.vsegs.length} expected`);
  } else {
    for (let i = 0; i < data.vsegs.length; i++) {
      const g = data.vsegs[i];
      const w = exp.vsegs[i];
      if (!near(g.x, w.x) || !near(g.y0, w.y0) || !near(g.y1, w.y1)) {
        errors.push(`${p} vseg ${i}: x=${g.x.toFixed(1)} y=${g.y0.toFixed(1)}..${g.y1.toFixed(1)} != x=${w.x.toFixed(1)} y=${w.y0.toFixed(1)}..${w.y1.toFixed(1)}`);
      }
    }
  }

  // --- boxes
  if (data.boxes.length !== exp.boxes.length) {
    errors.push(`${p}: ${data.boxes.length} boxes != ${exp.boxes.length} expected`);
  } else {
    for (let i = 0; i < data.boxes.length; i++) {
      if (!rectNear(data.boxes[i].rect, exp.boxes[i])) {
        errors.push(`${p} box ${i}: ${fmtRect(data.boxes[i].rect)} != [${exp.boxes[i].map((v: number) => v.toFixed(1)).join(" ")}]`);
      }
    }
  }

  // --- tables
  if (data.tables.length !== exp.tables.length) {
    errors.push(`${p}: ${data.tables.length} tables != ${exp.tables.length} expected `
      + `got=${JSON.stringify(data.tables.map((t) => t.rows.map((r) => r.length)))} want=${JSON.stringify(exp.tables.map((t: any) => t.rows.map((r: any) => r.length)))}`);
  } else {
    for (let ti = 0; ti < data.tables.length; ti++) {
      const gt = data.tables[ti];
      const wt = exp.tables[ti];
      if (!rectNear(gt.bbox, wt.bbox)) errors.push(`${p} table ${ti}: bbox ${fmtRect(gt.bbox)} != [${wt.bbox.map((v: number) => v.toFixed(1)).join(" ")}]`);
      if (gt.rows.length !== wt.rows.length) {
        errors.push(`${p} table ${ti}: ${gt.rows.length} rows != ${wt.rows.length}`);
        continue;
      }
      for (let ri = 0; ri < gt.rows.length; ri++) {
        const gr = gt.rows[ri];
        const wr = wt.rows[ri];
        if (gr.length !== wr.length) {
          errors.push(`${p} table ${ti} row ${ri}: ${gr.length} cells != ${wr.length} got cols=${JSON.stringify(gr.map((c) => c.col))} want cols=${JSON.stringify(wr.map((c: any) => c.col))}`);
          continue;
        }
        for (let ci = 0; ci < gr.length; ci++) {
          const gc = gr[ci];
          const wc = wr[ci];
          if (gc.col !== wc.col || gc.row !== wc.row) errors.push(`${p} table ${ti} r${ri}c${ci}: pos (${gc.row},${gc.col}) != (${wc.row},${wc.col})`);
          if (!rectNear(gc.rect, wc.rect)) errors.push(`${p} table ${ti} r${ri}c${ci}: rect ${fmtRect(gc.rect)} != [${wc.rect.map((v: number) => v.toFixed(1)).join(" ")}]`);
          if (gc.text !== wc.text) errors.push(`${p} table ${ti} r${ri}c${ci}: text ${JSON.stringify(gc.text)} != ${JSON.stringify(wc.text)}`);
        }
      }
    }
  }
}

function diffCandidates(cands: Candidate[], exp: any[], page: number, errors: string[]): void {
  const p = `p${page + 1}`;
  if (cands.length !== exp.length) {
    errors.push(`${p}: ${cands.length} candidates != ${exp.length} expected`);
  }
  const n = Math.min(cands.length, exp.length);
  for (let i = 0; i < n; i++) {
    const g = cands[i];
    const w = exp[i];
    const id = `${p} cand ${i} (${w.name})`;
    if (g.ftype !== w.ftype) errors.push(`${id}: ftype ${g.ftype} != ${w.ftype}`);
    if (g.label !== w.label) errors.push(`${id}: label ${JSON.stringify(g.label)} != ${JSON.stringify(w.label)}`);
    if (g.source !== w.source) errors.push(`${id}: source ${g.source} != ${w.source}`);
    if (g.name !== w.name) errors.push(`${id}: name ${JSON.stringify(g.name)} != ${JSON.stringify(w.name)}`);
    if (g.multiline !== w.multiline) errors.push(`${id}: multiline ${g.multiline} != ${w.multiline}`);
    if (!rectNear(g.rect, w.rect)) errors.push(`${id}: rect ${fmtRect(g.rect)} != [${w.rect.map((v: number) => v.toFixed(1)).join(" ")}]`);
  }
  if (cands.length !== exp.length) {
    const gotList = cands.map((c) => `${c.ftype}@${fmtRect(c.rect)} ${c.name || c.label}`);
    const wantList = exp.map((c) => `${c.ftype}@[${c.rect.map((v: number) => v.toFixed(1)).join(" ")}] ${c.name}`);
    for (let i = 0; i < Math.max(gotList.length, wantList.length); i++) {
      if (gotList[i] !== wantList[i]) {
        errors.push(`${p} cand ${i}: got ${gotList[i] ?? "-"} | want ${wantList[i] ?? "-"}`);
      }
    }
  }
}

// fixtures are derived from local sample PDFs and are not committed
// (personal data); regenerate with `npm run fixtures`
const fixtures = fs.existsSync(EXPECTED_DIR)
  ? fs.readdirSync(EXPECTED_DIR).filter((f) => f.endsWith(".json"))
  : [];

describe("parity with the Python pipeline", () => {
  if (!fixtures.length) {
    it.skip("no fixtures present — run `npm run fixtures` with local sample PDFs", () => {});
  }
  for (const fixtureName of fixtures) {
    const stem = fixtureName.replace(/\.json$/, "");
    it(stem, () => {
      const fixture: Fixture = JSON.parse(fs.readFileSync(path.join(EXPECTED_DIR, fixtureName), "utf8"));
      const pdfPath = findPdf(stem);
      expect(pdfPath, `sample PDF for ${stem}`).toBeTruthy();

      const doc = mupdf.Document.openDocument(fs.readFileSync(pdfPath!), "application/pdf") as mupdf.PDFDocument;
      const errors: string[] = [];
      const allCands: Candidate[] = [];
      const pageDatas: PageData[] = [];
      try {
        for (let i = 0; i < doc.countPages(); i++) {
          const page = doc.loadPage(i);
          const data = extractPage(page, i);
          pageDatas.push(data);
          allCands.push(...detect(data));
          page.destroy();
        }
      } finally {
        doc.destroy();
      }
      assignNames(allCands);

      for (const data of pageDatas) {
        diffPage(data, fixture.pages[data.number], errors);
      }
      for (let i = 0; i < fixture.pages.length; i++) {
        diffCandidates(allCands.filter((c) => c.page === i), fixture.pages[i].candidates, i, errors);
      }

      if (errors.length) {
        throw new Error(`${errors.length} mismatches:\n` + errors.slice(0, 60).join("\n"));
      }
    });
  }
});
